// components/tabs/translator-tab.tsx
"use client";

import { useState, useRef, useEffect } from "react";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import TextareaAutosize from "react-textarea-autosize";
import {
  Globe,
  Loader2,
  CheckCircle,
  Copy,
  Download,
  Languages,
  AlertCircle,
  Upload,
} from "lucide-react";
import { saveAs } from "file-saver";
import { readFileAsText, setupDragAndDrop } from "@/lib/file-utils";

import {
  translateText,
  detectLanguage,
  getLanguageName,
  getSupportedLanguages,
} from "@/lib/translator-unified";

const LANGUAGES = getSupportedLanguages();

export default function TranslatorTab() {
  const [inputText, setInputText] = useState("");
  const [sourceLanguage, setSourceLanguage] = useState("auto");
  const [targetLanguage, setTargetLanguage] = useState("es");
  const [translatedText, setTranslatedText] = useState("");
  const [detectedLang, setDetectedLang] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [downloadProgress, setDownloadProgress] = useState(0);
  const [copied, setCopied] = useState(false);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Auto-detect on text change (debounced)
  useEffect(() => {
    if (!inputText.trim() || sourceLanguage !== "auto") {
      setDetectedLang(null);
      return;
    }

    const timer = setTimeout(async () => {
      try {
        const detection = await detectLanguage(inputText);
        setDetectedLang(detection[0]?.detectedLanguage || null);
      } catch (e) {
        // Silent fail
      }
    }, 600);

    return () => clearTimeout(timer);
  }, [inputText, sourceLanguage]);

  // File upload
  useEffect(() => {
    if (textareaRef.current) {
      setupDragAndDrop(textareaRef.current, async (files) => {
        try {
          const content = await readFileAsText(files[0]);
          setInputText(content);
          setError("");
        } catch (err: any) {
          setError(err.message);
        }
      });
    }
  }, []);

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    try {
      const content = await readFileAsText(file);
      setInputText(content);
      setError("");
    } catch (err: any) {
      setError(err.message);
    }
    if (fileInputRef.current) fileInputRef.current.value = "";
  };

  const handleTranslate = async () => {
    if (!inputText.trim()) {
      setError("Please enter text to translate.");
      return;
    }

    setLoading(true);
    setError("");
    setTranslatedText("");
    setDownloadProgress(0);

    try {
      setDownloadProgress(30);

      let finalSource = sourceLanguage;
      if (sourceLanguage === "auto") {
        const detection = await detectLanguage(inputText);
        finalSource = detection[0]?.detectedLanguage || "en";
        setDetectedLang(finalSource);
      }

      setDownloadProgress(70);

      const result = await translateText(
        inputText,
        finalSource,
        targetLanguage,
        (p) => setDownloadProgress(p)
      );

      setTranslatedText(result);
      setDownloadProgress(100);
    } catch (e: any) {
      setError(e?.message || "Translation failed. Check your API key.");
    } finally {
      setLoading(false);
      setTimeout(() => setDownloadProgress(0), 1000);
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(translatedText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExport = () => {
    const sourceLang = LANGUAGES.find((l) => l.code === (detectedLang || sourceLanguage));
    const targetLang = LANGUAGES.find((l) => l.code === targetLanguage);

    const content = `Newsroom Forge - Translation Report
============================================

Original Text (${sourceLang?.name || "Auto"}):
${inputText}

---

Translated to ${targetLang?.name}:
${translatedText}

---
Generated by Newsroom Forge - Gemini 2.0 Flash
`;
    const blob = new Blob([content], { type: "text/plain" });
    saveAs(blob, `translation-${targetLanguage}-${Date.now()}.txt`);
  };

  const targetLang = LANGUAGES.find((l) => l.code === targetLanguage);

  return (
    <div className="space-y-4">
      {/* Input */}
      <motion.div className="glass-lg border border-white/10 p-6 rounded-3xl">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2">
            <Globe className="h-5 w-5 text-indigo-400" />
            <h3 className="font-semibold text-indigo-400">
              Source Text
              {detectedLang && sourceLanguage === "auto" && (
                <span className="ml-2 text-xs bg-indigo-500/20 px-2 py-1 rounded-full">
                  Detected: {getLanguageName(detectedLang)}
                </span>
              )}
            </h3>
          </div>
          <Button variant="outline" size="sm" onClick={() => fileInputRef.current?.click()}>
            <Upload className="w-4 h-4 mr-1" /> Upload
          </Button>
        </div>
        <input ref={fileInputRef} type="file" accept=".txt,.doc,.docx" onChange={handleFileUpload} className="hidden" />
        <TextareaAutosize
          ref={textareaRef}
          value={inputText}
          onChange={(e) => setInputText(e.target.value)}
          className="w-full bg-transparent text-base resize-none outline-none focus:ring-0"
          minRows={8}
          placeholder="Enter or upload text... (Auto-detect enabled)"
        />
      </motion.div>

      {/* Controls */}
      <motion.div className="glass-lg border border-white/10 p-6 rounded-3xl">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
          <div>
            <label className="block text-sm font-medium mb-2 flex items-center gap-2">
              <Languages className="h-4 w-4 text-indigo-400" />
              Source Language
            </label>
            <select
              value={sourceLanguage}
              onChange={(e) => setSourceLanguage(e.target.value)}
              className="w-full bg-white/5 border border-white/10 rounded-lg px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
              disabled={loading}
            >
              <option value="auto">Auto Detect</option>
              {LANGUAGES.map((lang) => (
                <option key={lang.code} value={lang.code}>
                  {lang.flag} {lang.name}
                </option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-sm font-medium mb-2 flex items-center gap-2">
              <Globe className="h-4 w-4 text-indigo-400" />
              Target Language
            </label>
            <select
              value={targetLanguage}
              onChange={(e) => setTargetLanguage(e.target.value)}
              className="w-full bg-white/5 border border-white/10 rounded-lg px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
              disabled={loading}
            >
              {LANGUAGES.map((lang) => (
                <option key={lang.code} value={lang.code}>
                  {lang.flag} {lang.name}
                </option>
              ))}
            </select>
          </div>
        </div>

          <Button
            onClick={handleTranslate}
            disabled={loading || !inputText.trim()}
            className="w-full bg-indigo-600 hover:bg-indigo-700 text-white"
          >
            {loading ? (
              <>
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                {downloadProgress < 60 ? "Detecting..." : "Translating..."}
              </>
            ) : (
              <>
                <Globe className="h-4 w-4 mr-2" />
                Translate to {targetLang?.name}
              </>
            )}
          </Button>

        {downloadProgress > 0 && downloadProgress < 100 && (
          <div className="mt-2">
            <div className="w-full bg-white/10 rounded-full h-2">
              <div
                className="bg-indigo-500 h-2 rounded-full transition-all duration-300"
                style={{ width: `${downloadProgress}%` }}
              />
            </div>
          </div>
        )}

        {error && (
          <div className="p-3 bg-red-500/10 border border-red-500/20 rounded-lg flex items-start gap-2 mt-2">
            <AlertCircle className="h-4 w-4 text-red-400 mt-0.5" />
            <p className="text-xs text-red-400">{error}</p>
          </div>
        )}
      </motion.div>

      {/* Output */}
      <motion.div className="glass-lg border border-white/10 p-6 rounded-3xl">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2">
            {loading ? (
              <Loader2 className="h-5 w-5 text-indigo-400 animate-spin" />
            ) : translatedText ? (
              <CheckCircle className="h-5 w-5 text-green-400" />
            ) : (
              <Globe className="h-5 w-5 text-muted-foreground" />
            )}
            <h3 className="font-semibold text-indigo-400">
              {translatedText ? `Translated (${targetLang?.flag} ${targetLang?.name})` : "Translation"}
            </h3>
          </div>

          {translatedText && (
            <div className="flex gap-2">
              <Button variant="outline" size="sm" onClick={handleCopy}>
                {copied ? "Copied!" : <Copy className="h-3.5 w-3.5" />}
              </Button>
              <Button variant="outline" size="sm" onClick={handleExport}>
                <Download className="h-3.5 w-3.5" />
              </Button>
            </div>
          )}
        </div>

        <div className="min-h-[200px] bg-white/5 rounded-lg p-4 border border-white/10">
          {translatedText ? (
            <p className="text-base leading-relaxed whitespace-pre-wrap">{translatedText}</p>
          ) : (
            <p className="text-muted-foreground italic text-sm">Translation will appear here...</p>
          )}
        </div>
      </motion.div>

      {/* Info */}
      <motion.div className="glass-news border border-white/10 p-4 rounded-2xl">
        <h4 className="text-sm font-semibold mb-2 flex items-center gap-2 text-indigo-400">
          <Globe className="h-4 w-4" />
          Gemini 2.0 Flash Translation
        </h4>
        <ul className="text-xs text-muted-foreground space-y-1">
          <li>150+ Languages • Auto-Detect • Instant</li>
          <li>Free Tier: 15 RPM • Export Reports</li>
        </ul>
      </motion.div>
    </div>
  );
}